---
title: "R group visualization"
author: "Zhu HongLu"
date: "4/22/2020"
output: html_document
---
```{r}
library(shiny)

library(WDI)

library(ggvis)
```

```{r}
library(WDI)
indicator2 <- WDI(country="all", indicator=c("NY.GDP.PCAP.CD", "SP.POP.TOTL", "SP.DYN.LE00.IN"), start=2011, end=2018, extra = TRUE)
drops <- c("iso2c","iso3c", "capital", "longitude", "latitude", "income", "lending")
indicator2 <- indicator2[ , !(names(indicator2) %in% drops)]
colnames(indicator2) <- c("country","year", "GDP_per_capita", "population_total", "life_expectancy", "region")
indicator2 <- indicator2[-c(1, 2, 3, 4, 5, 6, 19, 66, 67, 159, 178, 179, 180, 181, 182, 201, 202, 203, 204, 205, 206, 207, 225, 226, 227, 228, 236, 237, 238, 239, 240, 241, 242, 243, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 262, 263), ]

```

```{r}
ui <- fluidPage(
  sliderInput(inputId = "Year",
  label = h5("Select Year"),
  min = 2011,#as.Date(cv_min_date,"%Y-%m-%d"),
  max = 2018,#as.Date(current_date,"%Y-%m-%d"),
  value = 2018, #as.Date(current_date),
  timeFormat = '%Y',
  #timeFormat = "%d %b", 
  #animate=animationOptions(interval = 3000, loop = FALSE),
  ),
  plotOutput("graph")
)
```

```{r}
server <- function(input, output) {
  
  output$graph = renderPlot({
    
    indicator2 %>%
      ggvis(~GDP_per_capita, ~life_expectancy, fill=~factor(region)) %>%
      layer_points(size= ~population_total/1000000,opacity:=0.6) %>%
      add_legend(scales = "size", properties = legend_props(legend = list(y = 200))) %>%
      scale_numeric("y", domain = c(0, 90), nice = FALSE) %>%
      add_axis("x", title = "GDP per Capita(USD)") %>%
      add_axis("x", orient = "top", ticks = 0, title = "GDP per Capita vs. Life Expectancy 2019",
           properties = axis_props(
             axis = list(stroke = "white"),
             labels = list(fontSize = 0)))
  })

}


```

```{r}
shinyApp(ui = ui, server = server)
```

```{r}
library(ggvis)
indicator2 %>%
  ggvis(~GDP_per_capita, ~life_expectancy, fill=~factor(region)) %>%
  layer_points(size= ~population_total/1000000,opacity:=0.6) %>%
  add_legend(scales = "size", properties = legend_props(legend = list(y = 200))) %>%
  scale_numeric("y", domain = c(0, 90), nice = FALSE) %>%
  add_axis("x", title = "GDP per Capita(USD)") %>%
  add_axis("x", orient = "top", ticks = 0, title = "GDP per Capita vs. Life Expectancy 2019",
           properties = axis_props(
             axis = list(stroke = "white"),
             labels = list(fontSize = 0)))
```

```{r}
options(scipen=999)
radius <- sqrt( indicator2$population_total/ pi )
symbols(indicator2$GDP_per_capita, indicator2$life_expectancy, circles=radius, inches=0.35, fg="white", bg="red", xlab="GDP per Capita(USD)", ylab="Life Expectancy(years)", main = "GDP per Capita vs. Life Expectancy 2015", ylim = c(0, 100))

```

```{r}
library(plotly)
p <- plot_ly(indicator2, x = ~GDP_per_capita, y = ~life_expectancy,
  color = ~region, size = ~population_total) %>%
  layout(yaxis = list(range = c(0, 90)))
p
geom_smooth(method = lm, size = 0.5, se = FALSE)+transition_time(Year)
```

```{r}
# install.packages('tidyverse')
library(tidyverse)
# install.packages('gapminder')
library(gapminder)
source("https://github.com/traffordDataLab/assets/raw/master/theme/ggplot2/theme_lab.R")

df <- gapminder %>%
  filter(year == 2008 & continent == "Asia") %>%
  mutate(median = median(gdpPercap),
         diff = gdpPercap - median,
         type = ifelse(gdpPercap < median, "Below", "Above")) %>% 
  arrange(diff) %>% 
  mutate(country = factor(country, levels = country))

ggplot(df, aes(x = country, y = diff, label = country)) + 
  geom_col(aes(fill = type), width = 0.5, alpha = 0.8)  +
  scale_y_continuous(expand = c(0, 0), labels = scales::dollar) +
  scale_fill_manual(labels = c("Above median", "Below median"), 
                    values = c("Above" = "#31a354", "Below" = "#de2d26")) + 
  labs(title = "",
       subtitle = "GDP per capita, 2019",
       x = NULL,
       y = NULL,
       fill = NULL) + 
  coord_flip() +
  theme_lab() +
  theme(panel.grid.major.y = element_blank())

```

```{r}

df <- gapminder %>% 
  filter(country %in% c("France", "Germany", "Ireland", "Italy")) %>% 
  mutate(year = as.Date(paste(year, "-01-01", sep = "", format='%Y-%b-%d')))

ggplot(df, aes(x = year, y = gdpPercap, fill = country)) +
  geom_area(color = "white", alpha = 0.4) +
  scale_fill_brewer(palette = "Set2") +
  scale_x_date(breaks = df$year, date_labels = "%Y") +
  scale_y_continuous(expand = c(0, 0), labels = scales::dollar) +
  labs(title = "",
       subtitle = "GDP per capita by country, 2010-2019",
       caption = "Source: Gapminder.org  |  @traffordDataLab",
       x = NULL,
       y = "GDP per capita ($)",
       fill = NULL) +
  theme_lab() +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom")
```

```{r}

sliderInput(inputId = "Year",
                                                      label = h5("Select Year"),
                                                      min = 2011,#as.Date(cv_min_date,"%Y-%m-%d"),
                                                      max = 2018,#as.Date(current_date,"%Y-%m-%d"),
                                                      value = 2018, #as.Date(current_date),
                                                      timeFormat = '%Y',
                                                      #timeFormat = "%d %b", 
                                                      #animate=animationOptions(interval = 3000, loop = FALSE),
                                          )
```

